# Generated by Django 3.1.5 on 2021-01-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikesys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='endLocId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
